#!/command/with-contenv bash
# SPDX-FileCopyrightText: © 2026 Nfrastack <code@nfrastack.com>
#
# SPDX-License-Identifier: MIT

source /container/base/functions/container/init
output_off
showoff

mkdir -p "${CONTAINER_LOG_FILE_PATH}"
touch "${CONTAINER_LOG_FILE_PATH%/}"/"${CONTAINER_LOG_FILE_NAME}"
echo "** Container Name: ${CONTAINER_NAME} - Commencing Logging - Image: ${IMAGE_NAME}" >> "${CONTAINER_LOG_FILE_PATH%/}"/"${CONTAINER_LOG_FILE_NAME}"
call create_logrotate container "${CONTAINER_LOG_FILE_PATH%/}"/"${CONTAINER_LOG_FILE_NAME}"

if var_true "${CONTAINER_ENABLE_PERMISSIONS}" ; then
    print_debug "Enabling permissions features"
    unames+="$(set -o posix ; set | sort | grep -e '^CONTAINER_USER_' | sed "s|^CONTAINER_USER_||g" | tr '[:upper:]' '[:lower:]' | tr ' ' '\n')"
    for upair in $unames; do
        uname=$(echo "${upair}" | cut -d = -f 1)
        uid=$(echo "${upair}" | cut -d = -f 2)
        if grep -e "^${uname}" /etc/passwd > /dev/null; then
           _userexists=true
        elif grep -e "^${uname/_/-}" /etc/passwd > /dev/null; then
           _userexists=true
           uname=${uname/_/-}
        fi
        if [ "${_userexists}" = true ] ; then
            ouid=$(grep -e "^${uname}" /etc/passwd | awk -F: '{print $3}')

            print_debug "Changing user '${u}' to uid '${uid}' from '${ouid}'"
            sed -i "s|${uname}:x:${ouid}:|${uname}:x:${uid}:|g" /etc/passwd
        fi
    done
    groups+="$(set -o posix ; set | sort | grep -e '^CONTAINER_GROUP_' | sed "s|^CONTAINER_GROUP_||g" | tr '[:upper:]' '[:lower:]' | tr ' ' '\n' | sed '/add_.*/d' ) "
    for gpair in $groups; do
        gname=$(echo "${gpair}" | cut -d = -f 1)
        gid=$(echo "${gpair}" | cut -d = -f 2)
        if grep -e "^${gname}" /etc/group > /dev/null; then
           _groupexists=true
        elif grep -e "^${gname/_/-}" /etc/group > /dev/null; then
           _groupexists=true
           gname=${gname/_/-}
        fi

        if [ "${_groupexists}" = true ] ; then
            opgid=$(grep -e "^${gname}" /etc/passwd | awk -F: '{print $4}')
            og=$(grep -e "^${gname}" /etc/group | awk -F: '{print $1}')
            oggid=$(grep -e "^${gname}" /etc/group | awk -F: '{print $3}')
            print_debug "Changing group '${gname}' to gid '${gid}' from '${oggid}'"
            sed -i "s|\(.*\):\(.*\):\(.*\):${opgid}:|\1:\2:\3:${gid}:|g" /etc/passwd
            sed -i "s|${og}:x:${oggid}|${og}:x:${gid}|g" /etc/group
        fi
    done
    groupsadd+="$(set -o posix ; set | sort | grep -e '^CONTAINER_GROUP_ADD_' | sed 's|^CONTAINER_GROUP_ADD_||g' | tr '[:upper:]' '[:lower:]' )"
    for gapair in $groupsadd; do
        gname=$(echo "${gapair}" | cut -d = -f1 )
        if grep -e "^${gname}" /etc/group > /dev/null; then
           _groupexists=true
        elif grep -e "^${gname/_/-}" /etc/group > /dev/null; then
           _groupexists=true
           gname=${gname/_/-}
        else
            _groupexists=false
        fi
        if [ "${_groupexists}" = true ] ; then
            uta=$(echo ${gapair} | cut -d = -f2 | tr ',' '\n')
            for userstogroup in ${uta} ; do
                print_debug "Adding user '${userstogroup}' to '${gname}'"
                silent add_user_group ${userstogroup} ${gname}
            done
        fi
    done

    groupsdel+="$(set -o posix ; set | sort | grep -e '^CONTAINER_GROUP_DEL_' | sed 's|^CONTAINER_GROUP_DEL_||g' | tr '[:upper:]' '[:lower:]' )"
    for gapair in $groupsdel; do
        gname=$(echo "${gapair}" | cut -d = -f1 )
        if grep -e "^${gname}" /etc/group > /dev/null; then
           _groupexists=true
        elif grep -e "^${gname/_/-}" /etc/group > /dev/null; then
           _groupexists=true
           gname=${gname/_/-}
        else
            _groupexists=false
        fi
        if [ "${_groupexists}" = true ] ; then
            utd=$(echo ${gapair} | cut -d = -f2 | tr ',' '\n')
            for usersfromgroup in ${utd} ; do
                print_debug "Deleting user '${usersfromgroup}' from '${gname}'"
                silent delete_user_group ${usersfromgroup} ${gname}
            done
        fi
    done
fi

output_off

set_timezone "${TIMEZONE}"
host_override
rm -rf /etc/logrotate.d/*
output_on

liftoff
