name: build

on:
  workflow_call

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - { distro: "alpine", distro_variant: "edge", latest: "false", distro_latest: "false", arch: "linux/amd64,linux/arm64" }
          - { distro: "alpine", distro_variant: "3.23", latest: "true", distro_latest: "true", arch: "linux/amd64,linux/arm64" }
          - { distro: "alpine", distro_variant: "3.22", latest: "false", distro_latest: "false", arch: "linux/amd64,linux/arm64" }
          - { distro: "alpine", distro_variant: "3.19", latest: "false", distro_latest: "false", arch: "linux/amd64,linux/arm64" }
          - { distro: "alpine", distro_variant: "3.16", latest: "false", distro_latest: "false", arch: "linux/amd64,linux/arm64" }
          - { distro: "alpine", distro_variant: "3.15", latest: "false", distro_latest: "false", arch: "linux/amd64,linux/arm64" }
          - { distro: "alpine", distro_variant: "3.12", latest: "false", distro_latest: "false", arch: "linux/amd64,linux/arm64" }
          - { distro: "debian", distro_variant: "trixie", latest: "false", distro_latest: "true", arch: "linux/amd64,linux/arm64" }
          - { distro: "debian", distro_variant: "bookworm", latest: "false", distro_latest: "false", arch: "linux/amd64,linux/arm64" }
        image_variant:
          - core
          - faflopza
          - faflopzaze
        include:
          - image_variant: core
            image_base_modules: "+age,+cron,+logrotate,+s6overlay,+msmtp,"
            image_modules: ""
          - image_variant: faflopza
            image_base_modules: "+age,+cron,+logrotate,+s6overlay,+msmtp,"
            image_modules: "+fail2ban,+fluentbit,+openbao,+zabbix"
          - image_variant: faflopzaze
            image_base_modules: "+age,+cron,+logrotate,+s6overlay,+msmtp,"
            image_modules: "+fail2ban,+fluentbit,+openbao,+zabbix,+zerotier"
#  DISABLED by dup-sanitise Phase 3: uses: nfrastack/gha/.github/workflows/container-build_base.yml@main
    with:
      distro: ${{ matrix.build.distro }}
      distro_variant: ${{ matrix.build.distro_variant }}
      base_image_version: ${{ matrix.build.base_image_version || '' }}
      image_variant: ${{ matrix.image_variant }}
      latest: ${{ matrix.build.latest || 'false' }}
      distro_latest: ${{ matrix.build.distro_latest || 'false' }}
      platforms: ${{ matrix.build.arch || 'linux/amd64,linux/arm64' }}
      image_base_modules: ${{ matrix.image_base_modules }}
      image_modules: ${{ matrix.image_modules }}
    secrets: inherit
